# Score the models
print("KDD12:")
kdd12_log_loss = log_loss(np.round(kdd12_val['click']), kdd12_pipeline.predict_proba(kdd12_val.drop(columns=['click']))[:,1])
kdd12_roc_auc = roc_auc_score(np.round(kdd12_val['click']), kdd12_pipeline.predict_proba(kdd12_val.drop(columns=['click']))[:,1])
kdd12_accuracy = accuracy_score(np.round(kdd12_val['click']), kdd12_pipeline.predict(kdd12_val.drop(columns=['click'])))
print(f"Log loss: {kdd12_log_loss}")
print(f"ROC AUC: {kdd12_roc_auc}")
print(f"Accuracy: {kdd12_accuracy}")

print("\nAvazu:")
avazu_log_loss = log_loss(avazu_val['click'], avazu_pipeline.predict_proba(avazu_val.drop(columns=['click']))[:,1])
avazu_roc_auc = roc_auc_score(avazu_val['click'], avazu_pipeline.predict_proba(avazu_val.drop(columns=['click']))[:,1])
avazu_accuracy = accuracy_score(avazu_val['click'], avazu_pipeline.predict(avazu_val.drop(columns=['click'])))
print(f"Log loss: {avazu_log_loss}")
print(f"ROC AUC: {avazu_roc_auc}")
print(f"Accuracy: {avazu_accuracy}")

print("\nCriteo:")
criteo_log_loss = log_loss(criteo_val['click'], criteo_pipeline.predict_proba(criteo_val.drop(columns=['click']))[:,1])
criteo_roc_auc = roc_auc_score(criteo_val['click'], criteo_pipeline.predict_proba(criteo_val.drop(columns=['click']))[:,1])
criteo_accuracy = accuracy_score(criteo_val['click'], criteo_pipeline.predict(criteo_val.drop(columns=['click'])))
print(f"Log loss: {criteo_log_loss}")
print(f"ROC AUC: {criteo_roc_auc}")
print(f"Accuracy: {criteo_accuracy}")